#!/bin/bash

echo "🚀 Applying Migration 003 to Supabase"
echo "======================================="
echo ""
echo "The migration history has been synced, but migration 003 needs to be applied manually."
echo ""
echo "📋 Steps to apply migration 003:"
echo ""
echo "1. Open Supabase SQL Editor:"
echo "   https://supabase.com/dashboard/project/liepvjfiezgjrchbdwnb/sql/new"
echo ""
echo "2. Copy the SQL from:"
echo "   supabase/migrations/003_enhanced_schema.sql"
echo ""
echo "3. Paste it into the SQL Editor"
echo ""
echo "4. Click 'Run' to execute"
echo ""
echo "💡 Quick copy command:"
echo ""
echo "   cat supabase/migrations/003_enhanced_schema.sql"
echo ""
echo "Then copy the output and paste into Supabase SQL Editor."
echo ""
echo "🔍 What this migration does:"
echo "   ✅ Creates user_roles table for RBAC"
echo "   ✅ Creates employee_coupons table"
echo "   ✅ Creates commissions table"
echo "   ✅ Adds RLS policies to all tables"
echo "   ✅ Creates triggers for automatic commission tracking"
echo "   ✅ Adds quota checking functions"
echo ""
read -p "Press Enter to display the SQL migration file..."
echo ""
cat supabase/migrations/003_enhanced_schema.sql
