#!/bin/bash

echo "🔑 Supabase Configuration Helper"
echo "=================================="
echo ""
echo "✅ Service Role Key: Already configured"
echo "   sbp_34e88f18cf65aeab85605e03370dd41327e21841"
echo ""
echo "⚠️  MISSING: You still need to add:"
echo ""
echo "1️⃣  NEXT_PUBLIC_SUPABASE_URL"
echo "   📍 Find it at: https://app.supabase.com/project/_/settings/api"
echo "   📝 Format: https://xxxxx.supabase.co"
echo "   ⚡ Look for 'Project URL' section"
echo ""
echo "2️⃣  NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   📍 Same page as above"
echo "   📝 Format: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo "   ⚡ Look for 'Project API keys' > 'anon' > 'public'"
echo ""
echo "📝 How to complete setup:"
echo "   1. Visit https://app.supabase.com"
echo "   2. Select your project"
echo "   3. Go to Settings > API"
echo "   4. Copy the 'Project URL'"
echo "   5. Copy the 'anon public' key"
echo "   6. Add them to .env.local file"
echo ""
echo "💡 Quick edit command:"
echo "   nano .env.local"
echo ""
echo "🚀 After adding credentials, run:"
echo "   npm run dev"
echo ""
