import { NextRequest, NextResponse } from "next/server";
import { getServerSupabase } from "@/lib/supabase/server";
import { checkLetterQuota } from "@/lib/rls-helpers";

export async function POST(request: NextRequest) {
  try {
    const supabase = await getServerSupabase();
    const { data: { user }, error: authError } = await supabase.auth.getUser();

    if (authError || !user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Check quota
    const quota = await checkLetterQuota(user.id);
    if (!quota.canGenerate) {
      return NextResponse.json(
        { error: "Monthly letter limit reached. Please upgrade your subscription." },
        { status: 403 }
      );
    }

    // Parse request body
    const body = await request.json();
    const { title, content, recipient_name, recipient_address } = body;

    if (!title || !content) {
      return NextResponse.json(
        { error: "Title and content are required" },
        { status: 400 }
      );
    }

    // Create letter record with "generating" status
    const { data: letter, error: insertError } = await supabase
      .from("letters")
      .insert({
        user_id: user.id,
        title,
        content,
        recipient_name: recipient_name || null,
        recipient_address: recipient_address || null,
        status: "generating",
      })
      .select()
      .single();

    if (insertError) {
      console.error("Error creating letter:", insertError);
      return NextResponse.json(
        { error: "Failed to create letter" },
        { status: 500 }
      );
    }

    // In a production app, you would call an AI service here
    // For now, we'll simulate the generation and mark as completed
    // You can integrate with OpenAI, Claude, or your AI service
    
    // Simulate AI generation (in production, replace with actual AI call)
    const generatedContent = `
Dear ${recipient_name || "Recipient"},

${content}

This letter has been generated by Talk-To-My-Lawyer based on your provided information.

Sincerely,
[Your Name]
    `.trim();

    // Update letter status to completed
    const { error: updateError } = await supabase
      .from("letters")
      .update({
        status: "completed",
        content: generatedContent,
        completed_at: new Date().toISOString(),
      })
      .eq("id", letter.id);

    if (updateError) {
      console.error("Error updating letter:", updateError);
    }

    return NextResponse.json({
      success: true,
      letterId: letter.id,
      message: "Letter generated successfully",
    });
  } catch (error) {
    console.error("Error generating letter:", error);
    return NextResponse.json(
      { error: "Failed to generate letter" },
      { status: 500 }
    );
  }
}
